export const tailoredSolutions = [
  {
    category: 'Coaching <br/>& Consulting',
    items: [
      'Personal brand positioning for thought leadership',
      'High-value lead generation & client acquisition',
      'Authority-building strategies & trust-based marketing',
      'Pricing models & service monetization',
    ],
    image1: '/tailored/image1_1.png',
    image2: '/tailored/image1_2.png',
    image3: '/tailored/image1_3.png',
    buttonText: 'Coaching & Consulting',
  },
  {
    category: 'E-Commerce <br/>& Digital Products',
    items: [
      'Conversion-optimized online store strategies',
      'Customer experience & sales funnel optimization',
      'Automated sales & remarketing systems',
      'Product launch frameworks tailored for niche markets',
    ],
    image1: '/tailored/image2_1.png',
    image2: '/tailored/image2_2.png',
    image3: '/tailored/image2_3.png',
    buttonText: 'E-Commerce <br/>& Digital Products',
  },
  {
    category: 'Education <br/>& Online Courses',
    items: [
      'High-impact course positioning & curriculum structuring',
      'Digital learning engagement & student retention',
      'Paid & organic marketing strategies for course creators',
      'Scaling with membership models & certification programs',
    ],
    image1: '/tailored/image3_1.png',
    image2: '/tailored/image3_2.png',
    image3: '/tailored/image3_3.png',
    buttonText: 'Education <br/>& Online Courses',
  },
  {
    category: 'Health, Wellness <br/>& Lifestyle Brands',
    items: [
      'Influencer & expert-driven credibility building',
      'Community engagement & social trust strategies',
      'Subscription-based wellness program development',
      'Customer journey optimization for long-term loyalty',
    ],
    image1: '/tailored/image4_1.png',
    image2: '/tailored/image4_2.png',
    image3: '/tailored/image4_3.png',
    buttonText: 'Health, Wellness <br/>& Lifestyle Brands',
  },
  {
    category: 'Financial <br/>& Investment Advisory',
    items: [
      'Trust-building content & authority marketing',
      'Lead nurturing & customer relationship management',
      'Educational engagement strategies for complex services',
      'Scalable automation for client onboarding & retention',
    ],
    image1: '/tailored/image5_1.png',
    image2: '/tailored/image5_2.png',
    image3: '/tailored/image5_3.png',
    buttonText: 'Financial <br/>& Investment Advisory',
  },
  {
    category: 'Tech <br/>& SaaS Entrepreneurs',
    items: [
      'Product-market fit validation & beta-testing strategies',
      'Recurring revenue & subscription model refinement',
      'Demand generation & inbound marketing optimization',
      'Streamlining conversion funnels for user growth',
    ],
    image1: '/tailored/image6_1.png',
    image2: '/tailored/image6_2.png',
    image3: '/tailored/image6_3.png',
    buttonText: 'Tech <br/>& SaaS Entrepreneurs',
  },
];
