import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import { Footer } from '@/shared/ui/components/footer';
import { Header } from '@/shared/ui/components/header';

import './globals.css';
import './reset.css';
import 'modern-normalize/modern-normalize.css';

const outfitFont = Outfit({
  variable: '--font-outfit',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Marketfire',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfitFont.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
